# Generated by Django 3.2 on 2021-06-29 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=70)),
                ('tipo_vencimiento', models.CharField(choices=[('ALTA', 'Alta'), ('BAJA', 'Baja'), ('BAJA 51', 'Baja51'), ('BAJA 93', 'Baja93'), ('BAJA 85', 'Baja85'), ('BAJA 91', 'Baja91'), ('BAJA 53', 'Baja53'), ('BAJA 94', 'Baja94'), ('BAJA 54', 'Baja54'), ('REDUCCIÓN DE JORNADA', 'Redjor'), ('AMPLIACIÓN DE JORNADA', 'Ampljor'), ('INACTIVIDAD', 'Inact'), ('TRANSFORMACIÓN', 'Transf'), ('PROROGA', 'Prorr'), ('DESAFECTACIÓN', 'Desafec'), ('LLAMAMIENTO', 'Llamam'), ('BAJA Y ALTA', 'Bayal')], default='ALTA', max_length=25)),
                ('fechaBaja', models.DateField(null=True)),
                ('fechaAlta', models.DateField(null=True)),
                ('segSocial', models.BooleanField(default=False)),
                ('sepe', models.BooleanField(default=False)),
                ('enviadoContrato', models.BooleanField(default=False)),
                ('sage', models.BooleanField(default=False)),
                ('certificadoEmpresa', models.BooleanField(default=False)),
                ('envioLiquidacion', models.BooleanField(default=False)),
                ('firmaFY', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to='nucleo.empresa', verbose_name='Empresa')),
            ],
        ),
    ]
