# Generated by Django 3.2 on 2021-06-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_empleado_asesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='asesor',
            field=models.CharField(default='', max_length=25, null=True),
        ),
    ]
