# Generated by Django 3.2 on 2021-07-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0005_auto_20210702_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fechaAlta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fechaBaja',
            field=models.DateField(blank=True, null=True),
        ),
    ]
