# Generated by Django 3.2 on 2021-07-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0007_auto_20210702_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='asesor',
        ),
        migrations.AddField(
            model_name='empresa',
            name='asesor',
            field=models.CharField(choices=[('Elena', 'Elena'), ('JoseLuis', 'Joseluis'), ('Carmen', 'Carmen'), ('Maria', 'Maria'), ('Sara', 'Sara')], default='', max_length=25, null=True),
        ),
    ]
