# Generated by Django 3.2 on 2021-07-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0008_auto_20210705_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['fechaBaja']},
        ),
        migrations.AddField(
            model_name='empleado',
            name='fin',
            field=models.BooleanField(default=False),
        ),
    ]
