# Generated by Django 3.2 on 2021-07-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0009_auto_20210706_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='empleado',
            name='oculto',
            field=models.BooleanField(default=False),
        ),
    ]
