# Generated by Django 3.2 on 2021-07-08 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0010_auto_20210708_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['fecha']},
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='fechaAlta',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='fechaBaja',
        ),
    ]
